=== virtualphoton/some_cybernetic_scheisse/db/ISSpecs.dtd
<!ELEMENT BACKREFNAME ( #PCDATA ) >

<!ELEMENT DATA ( ENTITY+ ) >

<!ELEMENT DBMS ( TITLE, VERSION ) >

<!ELEMENT DESCRIPTION ( TITLE ) >

<!ELEMENT ENTITY ( PROPERTY+, RELATIONSHIP+ ) >
<!ATTLIST ENTITY ent_id NMTOKEN #REQUIRED >

<!ELEMENT ISSPECS ( DESCRIPTION, DATA, ROLES, TECHSPEC ) >

<!ELEMENT LANGUAGE ( TITLE, VERSION ) >

<!ELEMENT LIBRARY ( TITLE, VERSION ) >

<!ELEMENT NAME ( #PCDATA ) >

<!ELEMENT PROPERTY ( #PCDATA ) >

<!ELEMENT RELATIONSHIP ( NAME, TABLE, TYPE, BACKREFNAME ) >

<!ELEMENT RESPOSIBILITY ( #PCDATA ) >

<!ELEMENT ROLE ( TITLE, RESPOSIBILITY, TOTALUSERS ) >

<!ELEMENT ROLES ( ROLE+ ) >

<!ELEMENT TABLE ( #PCDATA ) >

<!ELEMENT TECHSPEC ( LIBRARY, DBMS, LANGUAGE ) >

<!ELEMENT TITLE ( #PCDATA ) >

<!ELEMENT TOTALUSERS ( #PCDATA ) >

<!ELEMENT TYPE ( #PCDATA ) >

<!ELEMENT VERSION ( #PCDATA ) >

=== virtualphoton/some_cybernetic_scheisse/db/ISSpecs.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no" ?>
<!DOCTYPE ISSPECS SYSTEM "ISSpecs.dtd">

<ISSPECS>
    <DESCRIPTION>
        <TITLE>Robot control system</TITLE>
    </DESCRIPTION>
    <DATA>
        <ENTITY ent_id="Machine">
            <PROPERTY>id</PROPERTY>
            <PROPERTY>name</PROPERTY>
            <PROPERTY>url</PROPERTY>
            <PROPERTY>js_path</PROPERTY>
            <PROPERTY>aruco_id</PROPERTY>
            <RELATIONSHIP>
                <NAME>specs</NAME>
                <TABLE>MachineSpec</TABLE>
                <TYPE>O-t-M</TYPE>
                <BACKREFNAME>machine</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>commands</NAME>
                <TABLE>Command</TABLE>
                <TYPE>O-t-M</TYPE>
                <BACKREFNAME>machine</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>holder</NAME>
                <TABLE>User</TABLE>
                <TYPE>M-t-O</TYPE>
                <BACKREFNAME>machines</BACKREFNAME>
            </RELATIONSHIP>
        </ENTITY>
        <ENTITY ent_id="MachineSpec">
            <PROPERTY>id</PROPERTY>
            <PROPERTY>name</PROPERTY>
            <RELATIONSHIP>
                <NAME>commands</NAME>
                <TABLE>Command</TABLE>
                <TYPE>M-t-M</TYPE>
                <BACKREFNAME>spec</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>machine</NAME>
                <TABLE>Machine</TABLE>
                <TYPE>M-t-O</TYPE>
                <BACKREFNAME>specs</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>groups</NAME>
                <TABLE>Group</TABLE>
                <TYPE>M-t-M</TYPE>
                <BACKREFNAME>machine_specs</BACKREFNAME>
            </RELATIONSHIP>
        </ENTITY>
        <ENTITY ent_id="Command">
            <PROPERTY>id</PROPERTY>
            <PROPERTY>name</PROPERTY>
            <RELATIONSHIP>
                <NAME>machine</NAME>
                <TABLE>Machine</TABLE>
                <TYPE>M-t-O</TYPE>
                <BACKREFNAME>commands</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>specs</NAME>
                <TABLE>MachineSpec</TABLE>
                <TYPE>M-t-M</TYPE>
                <BACKREFNAME>commands</BACKREFNAME>
            </RELATIONSHIP>
        </ENTITY>
        <ENTITY ent_id="Camera">
            <PROPERTY>id</PROPERTY>
            <PROPERTY>name</PROPERTY>
            <PROPERTY>connection</PROPERTY>
            <PROPERTY>address</PROPERTY>
            <PROPERTY>res_x</PROPERTY>
            <PROPERTY>res_y</PROPERTY>
            <RELATIONSHIP>
                <NAME>holder</NAME>
                <TABLE>User</TABLE>
                <TYPE>M-t-O</TYPE>
                <BACKREFNAME>cameras</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>groups</NAME>
                <TABLE>Group</TABLE>
                <TYPE>M-t-M</TYPE>
                <BACKREFNAME>cameras</BACKREFNAME>
            </RELATIONSHIP>
        </ENTITY>
        <ENTITY ent_id="User">
            <PROPERTY>id</PROPERTY>
            <PROPERTY>username</PROPERTY>
            <PROPERTY>role</PROPERTY>
            <RELATIONSHIP>
                <NAME>cameras</NAME>
                <TABLE>Camera</TABLE>
                <TYPE>O-t-M</TYPE>
                <BACKREFNAME>holder</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>machines</NAME>
                <TABLE>Machine</TABLE>
                <TYPE>O-t-M</TYPE>
                <BACKREFNAME>holder</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>groups_created</NAME>
                <TABLE>Group</TABLE>
                <TYPE>O-t-M</TYPE>
                <BACKREFNAME>creator</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>groups_member</NAME>
                <TABLE>Group</TABLE>
                <TYPE>M-t-M</TYPE>
                <BACKREFNAME>users</BACKREFNAME>
            </RELATIONSHIP>
        </ENTITY>
        <ENTITY ent_id="Group">
            <PROPERTY>id</PROPERTY>
            <RELATIONSHIP>
                <NAME>creator</NAME>
                <TABLE>User</TABLE>
                <TYPE>M-t-O</TYPE>
                <BACKREFNAME>groups_created</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>users</NAME>
                <TABLE>User</TABLE>
                <TYPE>M-t-M</TYPE>
                <BACKREFNAME>groups_member</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>cameras</NAME>
                <TABLE>Camera</TABLE>
                <TYPE>M-t-M</TYPE>
                <BACKREFNAME>groups</BACKREFNAME>
            </RELATIONSHIP>
            <RELATIONSHIP>
                <NAME>machine_specs</NAME>
                <TABLE>MachineSpec</TABLE>
                <TYPE>M-t-M</TYPE>
                <BACKREFNAME>groups</BACKREFNAME>
            </RELATIONSHIP>
        </ENTITY>
    </DATA>
    <ROLES>
	    <ROLE>
            <TITLE>User</TITLE>
            <RESPOSIBILITY>зарегистрированный пользователь, создающий группы</RESPOSIBILITY>
            <TOTALUSERS>unlimited</TOTALUSERS>
        </ROLE>
        <ROLE>
            <TITLE>Admin</TITLE>
            <RESPOSIBILITY>администратор, раздающий права владения камерами и машинами</RESPOSIBILITY>
            <TOTALUSERS>1</TOTALUSERS>
        </ROLE>
	    <ROLE>
            <TITLE>Guest</TITLE>
            <RESPOSIBILITY>гость, способный состоять в группах</RESPOSIBILITY>
            <TOTALUSERS>NOT LIMITED</TOTALUSERS>
        </ROLE>
    </ROLES>
    <TECHSPEC>
        <LIBRARY>
            <TITLE>Flask-SQLAlchemy</TITLE>
            <VERSION>3.0.2</VERSION>
        </LIBRARY>
        <DBMS>
            <TITLE>SQLite</TITLE>
            <VERSION>3</VERSION>
        </DBMS>
        <LANGUAGE>
            <TITLE>Python</TITLE>
            <VERSION>3.10.6</VERSION>
        </LANGUAGE>
    </TECHSPEC>
</ISSPECS>
